version: "3.7"

services:
  database_desafio_chapter04:
    image: postgres
    container_name: database_desafio_chapter04
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local